services:
  - type: web
    name: scheduler-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn scheduler.wsgi
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: scheduler-db
          property: connectionString
databases:
  - name: scheduler-db
