from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from .views import (
    RegisterView,
    ScheduleCreateView,
    ScheduleListView,
    ScheduleInviteView,
    ScheduleMemberListView,
    ScheduleSettingsUpdateView,
    ShiftCreateView,
    ShiftListView,
    ShiftSwapRequestView,
    ShiftSwapApproveView,
    ShiftSwapAdminApproveView,
    IncomingSwapRequestsView,
    TimeOffRequestCreateView,
    TimeOffRequestManageView,
    TimeOffRequestListView,
    ActivateUserView,
    UserSettingsView,
    ResendActivationView,
    UserProfileUpdateView,
    CalendarCreateView, 
    CalendarListView,
    CalendarInviteView,
    CalendarJoinByCodeView,
    CalendarMemberListView,
    CalendarDetailView,
    CalendarLookupByCodeView,
    ShiftSwapRequestListView,
    ShiftSwapAcceptView,
    ShiftSwapRejectView,
    ShiftTakeRequestView,
    ShiftTakeAcceptView,
    ShiftTakeRejectView,
    ShiftTakeRequestListView,
    InboxNotificationListView,
    InboxUnreadCountView,
    InboxNotificationDetailView,
    ShiftDetailView,
    CalendarShiftListView,
    ShiftSwapCancelView,
    ShiftTakeCancelView,
    ScheduleEditView,
    ScheduleDeleteView,
    ShiftDeleteView,
    RequestOffCreateView,
    TimeOffListView,
    TimeOffRequestDeleteView,
    WorkplaceHolidayListCreateView,
    WorkplaceHolidayDeleteView,

    
)


urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('schedules/create/', ScheduleCreateView.as_view(), name='schedule-create'),
    path('schedules/', ScheduleListView.as_view(), name='schedule-list'),
    path('schedules/<int:schedule_id>/invite/', ScheduleInviteView.as_view(), name='schedule-invite'),
    path('schedules/<int:schedule_id>/members/', ScheduleMemberListView.as_view(), name='schedule-members'),
    path('schedules/<int:schedule_id>/shifts/create/', ShiftCreateView.as_view(), name='shift-create'),
    path('schedules/<int:schedule_id>/shifts/', ShiftListView.as_view(), name='shift-list'),
    path('time-off/request/', TimeOffRequestCreateView.as_view(), name='time-off-create'),
    path('time-off/manage/<int:request_id>/', TimeOffRequestManageView.as_view(), name='time-off-manage'),
    path('schedules/<int:schedule_id>/time-off/', TimeOffRequestListView.as_view(), name='time-off-list'),
    path('shifts/request-swap/', ShiftSwapRequestView.as_view(), name='shift-request-swap'),
    path('shifts/<int:shift_id>/approve-swap/', ShiftSwapApproveView.as_view(), name='shift-approve-swap'),
    path('shifts/<int:shift_id>/reject-swap/', ShiftSwapRejectView.as_view(), name='shift-reject-swap'),
    path('shifts/my-incoming-swaps/', IncomingSwapRequestsView.as_view(), name='my-incoming-swaps'),
    path('schedules/<int:schedule_id>/settings/', ScheduleSettingsUpdateView.as_view(), name='schedule-settings'),
    path('shifts/swap/request/', ShiftSwapRequestView.as_view(), name='shift-swap-request'),
    path('shifts/swap/approve/', ShiftSwapApproveView.as_view(), name='shift-swap-approve'),
    path('shifts/swap/admin-approve/', ShiftSwapAdminApproveView.as_view(), name='shift-swap-admin-approve'),
    path('activate/<uidb64>/<token>/', ActivateUserView.as_view(), name='activate-user'),
    path('user/settings/', UserSettingsView.as_view(), name='user-settings'),
    path('resend-activation/', ResendActivationView.as_view(), name='resend-activation'),
    path('profile/', UserProfileUpdateView.as_view(), name='user-profile'),
    path('calendars/', CalendarListView.as_view(), name='calendar-list'),
    path('calendars/create/', CalendarCreateView.as_view(), name='calendar-create'),
    path('calendars/<int:calendar_id>/invite/', CalendarInviteView.as_view(), name='calendar-invite'),
    path('calendars/join/', CalendarJoinByCodeView.as_view(), name='calendar-join'),
    path('calendars/<int:calendar_id>/members/', CalendarMemberListView.as_view(), name='calendar-members'),
    path('calendars/<int:pk>/', CalendarDetailView.as_view(), name='calendar-detail'),
    path('calendars/lookup/', CalendarLookupByCodeView.as_view(), name='calendar-lookup'),
    path('user/', UserProfileUpdateView.as_view(), name='user-profile'),
    path('shifts/swap/requests/', ShiftSwapRequestListView.as_view(), name='shift-swap-requests'),
    path('shifts/swap/<int:swap_id>/accept/', ShiftSwapAcceptView.as_view(), name='shift-swap-accept'),
    path('shifts/swap/<int:swap_id>/reject/', ShiftSwapRejectView.as_view(), name='shift-swap-reject'),
    path('shifts/take/request/', ShiftTakeRequestView.as_view(), name='shift-take-request'),
    path('shifts/take/<int:take_id>/accept/', ShiftTakeAcceptView.as_view(), name='shift-take-accept'),
    path('shifts/take/<int:take_id>/reject/', ShiftTakeRejectView.as_view(), name='shift-take-reject'),
    path("shifts/take/requests/", ShiftTakeRequestListView.as_view()),
    path('inbox/', InboxNotificationListView.as_view(), name='inbox'),
    path('inbox/unread-count/', InboxUnreadCountView.as_view()),
    path('inbox/<int:pk>/', InboxNotificationDetailView.as_view()),
    path('shifts/<int:pk>/', ShiftDetailView.as_view()),
    path('calendars/<int:calendar_id>/shifts/', CalendarShiftListView.as_view()),
    path('swap/cancel/<int:swap_id>/', ShiftSwapCancelView.as_view(), name='swap-cancel'),
    path('take/cancel/<int:take_id>/', ShiftTakeCancelView.as_view(), name='take-cancel'),
    path('schedules/<int:pk>/edit/', ScheduleEditView.as_view()),
    path('schedules/<int:pk>/delete/', ScheduleDeleteView.as_view(), name='schedule-delete'),
    path('shifts/<int:pk>/delete/', ShiftDeleteView.as_view(), name='shift-delete'),
    path('calendars/<int:calendar_id>/request-off/', RequestOffCreateView.as_view()),
    path('time-off/', TimeOffListView.as_view(), name='time-off-list'),
    path('calendars/<int:calendar_id>/request-off/<int:pk>/delete/', TimeOffRequestDeleteView.as_view(), name='timeoff-delete'),
    path('calendars/<int:calendar_id>/holidays/', WorkplaceHolidayListCreateView.as_view(), name='workplaceholiday-list-create'),
    path('calendars/<int:calendar_id>/holidays/<int:pk>/delete/', WorkplaceHolidayDeleteView.as_view(), name='workplaceholiday-delete'),

]
