# Generated by Django 4.2.21 on 2025-05-21 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='require_admin_swap_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shift',
            name='swap_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.shift'),
        ),
    ]
