# Generated by Django 4.2.21 on 2025-05-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarmembership',
            old_name='role',
            new_name='title',
        ),
        migrations.AddField(
            model_name='calendarmembership',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
