# Generated by Django 4.2.21 on 2025-05-26 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_notify_email_user_notify_sms_user_pronouns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.calendar'),
        ),
    ]
