# Generated by Django 4.2.21 on 2025-05-31 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shiftswaprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='require_admin_swap_approval',
            field=models.BooleanField(default=False),
        ),
    ]
