# Generated by Django 4.2.21 on 2025-06-01 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_shifttakerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('SWAP_REQUEST', 'Swap Request'), ('TAKE_REQUEST', 'Take Request'), ('SCHEDULE_RELEASE', 'Schedule Release'), ('REQUEST_OFF_APPROVAL', 'Request Off Approval')], max_length=32)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
