# Generated by Django 4.2.21 on 2025-06-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_inboxnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxnotification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
