# Generated by Django 4.2.21 on 2025-06-02 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_inboxnotification_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxnotification',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.calendar'),
        ),
    ]
