# Generated by Django 4.2.21 on 2025-06-04 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_inboxnotification_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkplaceHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('off', 'Day Off'), ('half', 'Half Day'), ('custom', 'Custom Hours')], max_length=10)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.calendar')),
            ],
        ),
    ]
