# Generated by Django 4.2.21 on 2025-06-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_workplaceholiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplaceholiday',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
