# Generated by Django 4.2.21 on 2025-06-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_workplaceholiday_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='self_role_change_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
