# Generated by Django 4.2.21 on 2025-06-10 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_calendar_self_role_change_allowed'),
    ]

    operations = [
    ]
