# Generated by Django 4.2.21 on 2025-06-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_calendarpermission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarmembership',
            name='excluded_permissions',
            field=models.ManyToManyField(blank=True, related_name='excluded_from_members', to='core.calendarpermission'),
        ),
    ]
