# Generated by Django 4.2.21 on 2025-06-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_calendarmembership_excluded_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
