# Generated by Django 4.2.21 on 2025-06-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_shift_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='allow_swap_without_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendar',
            name='require_take_approval',
            field=models.BooleanField(default=True),
        ),
    ]
