# Generated by Django 4.2.21 on 2025-06-12 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_calendar_allow_swap_without_approval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='require_admin_swap_approval',
        ),
    ]
