# Generated by Django 4.2.21 on 2025-06-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_schedule_require_admin_swap_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='require_admin_swap_approval',
        ),
        migrations.AlterField(
            model_name='calendar',
            name='allow_swap_without_approval',
            field=models.BooleanField(default=True),
        ),
    ]
