# Generated by Django 4.2.21 on 2025-06-12 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_shift_require_admin_swap_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoffrequest',
            name='calendar',
            field=models.ForeignKey(default=46, on_delete=django.db.models.deletion.CASCADE, to='core.calendar'),
            preserve_default=False,
        ),
    ]
