# Generated by Django 4.2.21 on 2025-06-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_timeoffrequest_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoffrequest',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='visible_to_others',
            field=models.BooleanField(default=False),
        ),
    ]
