# Generated by Django 4.2.21 on 2025-06-14 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20250613_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxnotification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inboxnotification',
            name='sender_display',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inboxnotification',
            name='notification_type',
            field=models.CharField(choices=[('SWAP_REQUEST', 'Swap Request'), ('TAKE_REQUEST', 'Take Request'), ('SCHEDULE_RELEASE', 'Schedule Release'), ('REQUEST_OFF_APPROVAL', 'Request Off Approval'), ('ANNOUNCEMENT', 'Announcement')], max_length=32),
        ),
    ]
