# Generated by Django 4.2.21 on 2025-06-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_scheduleconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxnotification',
            name='notification_type',
            field=models.CharField(choices=[('SWAP_REQUEST', 'Swap Request'), ('TAKE_REQUEST', 'Take Request'), ('SCHEDULE_RELEASE', 'Schedule Release'), ('REQUEST_OFF_APPROVAL', 'Request Off Approval'), ('ANNOUNCEMENT', 'Announcement')], max_length=32),
        ),
    ]
