# Generated by Django 4.2.21 on 2025-06-14 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_inboxnotification_notification_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduleconfirmation',
            unique_together={('user', 'schedule')},
        ),
    ]
