# Generated by Django 4.2.21 on 2025-06-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_scheduleconfirmation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftswaprequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftswaprequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
