# Generated by Django 4.2.21 on 2025-06-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_shiftswaprequest_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttakerequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
