# Generated by Django 4.2.21 on 2025-06-18 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_calendarinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarinvite',
            name='resolved_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_calendar_invites', to=settings.AUTH_USER_MODEL),
        ),
    ]
