# Generated by Django 4.2.21 on 2025-06-18 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_calendarinvite_resolved_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarinvite',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_calendar_invites', to=settings.AUTH_USER_MODEL),
        ),
    ]
