# Generated by Django 4.2.21 on 2025-06-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_user_options_user_core_user_email_38052c_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxnotification',
            name='related_object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
