# Generated by Django 4.2.21 on 2025-06-22 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_inboxnotification_related_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftswaprequest',
            name='requesting_original_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftswaprequest',
            name='target_original_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='show_middle_name',
            field=models.BooleanField(default=False),
        ),
    ]
